### ISSUE TITLE
Error when leaving the server

### ISSUE THREAD

**Issue by CrushedPixel** [MCMDEV/BetterProtocol#1]
```
[21:17:49] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to BetterProtocol v1.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:3096-Spigot-9fb885e-296df56]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:3096-Spigot-9fb885e-296df56]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[server.jar:3096-Spigot-9fb885e-296df56]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[server.jar:3096-Spigot-9fb885e-296df56]
	at net.minecraft.server.v1_16_R3.PlayerList.disconnect(PlayerList.java:487) ~[server.jar:3096-Spigot-9fb885e-296df56]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1637) ~[server.jar:3096-Spigot-9fb885e-296df56]
	at net.minecraft.server.v1_16_R3.NetworkManager.handleDisconnection(NetworkManager.java:333) ~[server.jar:3096-Spigot-9fb885e-296df56]
	at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:163) ~[server.jar:3096-Spigot-9fb885e-296df56]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1246) ~[server.jar:3096-Spigot-9fb885e-296df56]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:394) ~[server.jar:3096-Spigot-9fb885e-296df56]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1127) ~[server.jar:3096-Spigot-9fb885e-296df56]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:966) ~[server.jar:3096-Spigot-9fb885e-296df56]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[server.jar:3096-Spigot-9fb885e-296df56]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302]
Caused by: java.util.NoSuchElementException: better_protocol_incoming_listener
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1119) ~[server.jar:3096-Spigot-9fb885e-296df56]
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:451) ~[server.jar:3096-Spigot-9fb885e-296df56]
	at de.mcmdev.betterprotocol.bukkit.inject.Injector.uninject(Injector.java:24) ~[?:?]
	at de.mcmdev.betterprotocol.bukkit.BetterProtocolBukkitPlugin$1.lambda$onQuit$1(BetterProtocolBukkitPlugin.java:43) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_302]
	at de.mcmdev.betterprotocol.bukkit.BetterProtocolBukkitPlugin$1.onQuit(BetterProtocolBukkitPlugin.java:43) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_302]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_302]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_302]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_302]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:3096-Spigot-9fb885e-296df56]
	... 13 more
[21:17:49] [Server thread/INFO]: CrPxl left the game
```

**Comment by mcmdev** [comment]
The issue has now been fixed. Thanks for reporting!
